exclude_paths:
  - vendor
  - tmp
  - bin
  - node_modules
  - db
  - test

detectors:
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 10
  UtilityFunction:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2


directories:
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "app/forms":
    Attribute:
      enabled: false
  "app/models":
    Attribute:
      enabled: false
