require:
  - rubocop-rails

AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/**/*"
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - spec/**/*
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
    - test/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Naming/RescuedExceptionsVariableName:
  PreferredName: error
