require:
  - rubocop-performance
  - rubocop-rails
  - syntax_tree

inherit_gem:
  syntax_tree: config/rubocop.yml

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/**/*"

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/SkipsModelValidations:
  Enabled: false
