default: &default
  requests_interval: <%= 5.seconds %>
  max_timeout: <%= 25.seconds %>

development:
  <<: *default

test:
  <<: *default
  requests_interval: <%= 0.seconds %>

production:
  <<: *default
