development:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 7) %>
    host: <%= ENV.fetch("PGHOST", "localhost") %>
    port: <%= ENV.fetch("PGPORT", 5432) %>
    username: <%= ENV.fetch("PGUSER", "postgres") %>
    password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
    database: malheatmap_development
    migrations_paths: "db/primary/migrate"

  cache:
    adapter: sqlite3
    database: "db/cache/development.sqlite3"
    pool: 5
    timeout: 5000
    migrations_paths: "db/cache/migrate"

test:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 7) %>
    host: <%= ENV.fetch("PGHOST", "localhost") %>
    port: <%= ENV.fetch("PGPORT", 5432) %>
    username: <%= ENV.fetch("PGUSER", "postgres") %>
    password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
    database: malheatmap_test
    migrations_paths: "db/primary/migrate"

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 7) %>
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: "db/primary/migrate"
  cache:
    adapter: sqlite3
    database: "db/cache/production.sqlite3"
    pool: 5
    timeout: 5000
    migrations_paths: "db/cache/migrate"
