default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 7) %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>

development:
  <<: *default
  database: malheatmap_development

test:
  <<: *default
  database: malheatmap_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
