sqlite_defaults: &sqlite_defaults
  adapter: sqlite3
  # Solid queue takes two queries by default + number of queue threads
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  default_transaction_mode: immediate
  pragmas:
    mmap_size: 64000000

development:
  primary:
    <<: *sqlite_defaults
    database: "storage/malheatmap_primary_development.sqlite3"
    migrations_paths: "db/migrate"
  ops:
    <<: *sqlite_defaults
    database: "storage/malheatmap_ops_development.sqlite3"
    migrations_paths: "db/ops/migrate"
  queues:
    <<: *sqlite_defaults
    database: "storage/malheatmap_queues_development.sqlite3"
    migrations_paths: "db/queues/migrate"

test:
  primary:
    <<: *sqlite_defaults
    database: "storage/malheatmap_primary_test.sqlite3"
    migrations_paths: "db/migrate"
  ops:
    <<: *sqlite_defaults
    database: "storage/malheatmap_ops_test.sqlite3"
    migrations_paths: "db/ops/migrate"
  queues:
    <<: *sqlite_defaults
    database: "storage/malheatmap_queues_test.sqlite3"
    migrations_paths: "db/queues/migrate"

production:
  primary:
    <<: *sqlite_defaults
    database: "storage/malheatmap_primary_production.sqlite3"
    migrations_paths: "db/migrate"
    pragmas:
      mmap_size: 256000000
  ops:
    <<: *sqlite_defaults
    database: "storage/malheatmap_ops_production.sqlite3"
    migrations_paths: "db/ops/migrate"
  queues:
    <<: *sqlite_defaults
    database: "storage/malheatmap_queues_production.sqlite3"
    migrations_paths: "db/queues/migrate"
