sqlite_defaults: &sqlite_defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  primary:
    <<: *sqlite_defaults
    database: "storage/malheatmap_primary_development.sqlite3"
    migrations_paths: "db/migrate"
  cache:
    <<: *sqlite_defaults
    database: "storage/malheatmap_cache_development.sqlite3"
    migrations_paths: "db/cache/migrate"

test:
  primary:
    <<: *sqlite_defaults
    database: "storage/malheatmap_primary_test.sqlite3"
    migrations_paths: "db/migrate"

production:
  primary:
    <<: *sqlite_defaults
    database: "storage/malheatmap_primary_production.sqlite3"
    migrations_paths: "db/migrate"
  cache:
    <<: *sqlite_defaults
    database: "storage/malheatmap_cache_production.sqlite3"
    migrations_paths: "db/cache/migrate"
