postgres_defaults: &postgres_defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 7) %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
  migrations_paths: "db/primary/migrate"

sqlite_defaults: &sqlite_defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000
  migrations_paths: "db/cache/migrate"

development:
  primary:
    <<: *postgres_defaults
    database: malheatmap_development
  cache:
    <<: *sqlite_defaults
    database: "storage/cache_development.sqlite3"

test:
  primary:
    <<: *postgres_defaults
    database: malheatmap_test

production:
  primary:
    <<: *postgres_defaults
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *sqlite_defaults
    database: "storage/cache_production.sqlite3"
