development:
  client_id: <%= ENV.fetch("MAL_API_CLIENT_ID", "dummy") %>
  client_secret: <%= ENV.fetch("MAL_API_CLIENT_SECRET", "dummy") %>

production:
  client_id: <%= Rails.application.credentials.mal_api&.client_id! %>
  client_secret: <%= Rails.application.credentials.mal_api&.client_secret! %>

test:
  client_id: <%= ENV.fetch("MAL_API_CLIENT_ID", "dummy") %>
  client_secret: <%= ENV.fetch("MAL_API_CLIENT_SECRET", "dummy") %>
