default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [within_30_seconds, within_3_minutes, solid_queue_recurring]
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.5
    - queues: [within_20_hours]
      threads: 1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
