default: &default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/5") %>
  pool:
    timeout: 5
    size: 10

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/15") %>

production:
  <<: *default
