default: &default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>
  pool_size: 10
  pool_timeout: 5

development:
  <<: *default

test:
  <<: *default
  db: 15

production:
  <<: *default
