default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        periodic_sync:
          class: User::SchedulePeriodicMALSyncJob
          schedule: every 5 minutes
        backups_job:
          class: RakeJob
          schedule: "every day at 5 pm on America/Sao_Paulo"
          args: ["backups:perform"]
        clean_up_job:
          class: CronJob
          schedule: "every 48 hours"
          args: ["SolidQueue::Job.clear_finished_in_batches"]
  workers:
    - queues: [default, active_storage]
      threads: 2
      processes: 1
      polling_interval: 1
    - queues: [low]
      threads: 1
      polling_interval: 5
      processes: 1
    - queues: [logging]
      threads: 1
      polling_interval: 30
      processes: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
