 default: &default
   dispatchers:
     - polling_interval: 1
       batch_size: 500
   workers:
     - queues: [default, active_storage]
       threads: 2
       processes: 1
       polling_interval: 0.1
     - queues: [low]
       threads: 2
       polling_interval: 5
       processes: 1
     - queues: [logging]
       threads: 1
       polling_interval: 10
       processes: 1

 development:
  <<: *default

 test:
  <<: *default

 production:
  <<: *default
