default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        periodic_sync:
          class: "User::SchedulePeriodicMALSyncJob"
          schedule: "every day at 6:00 and 18:00 on UTC"
        backups_job:
          class: "RakeJob"
          schedule: "every day at 12 pm on America/Sao_Paulo"
          args: [ "backups:perform" ]
        clean_up_job:
          class: "CronJob"
          schedule: "every 48 hours"
          args: [ "SolidQueue::Job.clear_finished_in_batches" ]
  workers:
    - queues: [default, chrome, active_storage, logging]
      threads: 3
      processes: 1
      polling_interval: 1
    - queues: [low]
      threads: 1
      processes: 1
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
