local:
  service: Disk
  root: <%= ENV["RAILS_STORAGE_PATH"].present? ? File.join(ENV["RAILS_STORAGE_PATH"], Rails.env) : Rails.root.join("storage", Rails.env) %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

