local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage", Rails.env) %>

google_cloud_storage:
  service: GCS
  project: mal-heatmap
  credentials: <%= Rails.application.credentials.google_cloud_service_key.to_json %>
  bucket: malheatmapsignatures
