on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        ports: ["5432:5432"]
      redis:
        image: redis:alpine
        ports: ["6379:6379"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache Ruby Dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Cache Node Dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install PostgreSQL Client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Run Linters and Test Suites
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        bin/setup
        bin/qa

    - name: Upload failed tests screenshots
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: system-tests-screenshots
        path: tmp/screenshots
